### ISSUE TITLE
Document access control

### ISSUE THREAD

**Issue by ArthurClemens** [arjan/zclient#1]
With mod_acl_simple_roles enabled, my external developer could not go to /oauth/authorize. The source code says that the user must have access to mod_admin.
Access should either be loosened or documented.

**Comment by arjan** [comment]
Yeah this looks like a bug to me here:

https://github.com/zotonic/zotonic/blob/master/modules/mod_oauth/controllers/controller_oauth_authorize.erl#L38

You can change it to check access to `mod_oauth` instead of `mod_admin`.

**Comment by arjan** [comment]
This was probably copypasted from here:
https://github.com/zotonic/zotonic/blob/master/modules/mod_oauth/controllers/controller_oauth_apps.erl#L32

(for that controller, `mod_admin` seems correct to me, btw)

**Comment by ArthurClemens** [comment]
Giving access to mod_oauth seems strange, the user only needs to press a button.

Why is an access check needed? The url with generated id times out, so passing the url around is useless.

**Comment by arjan** [comment]
true.. you can remove the whole check, I guess

**Comment by ArthurClemens** [comment]
No idea how to remove the check. I have changed it to `mod_oauth` now.
